### PR TITLE
chore: store examples in YAML

### PR DESCRIPTION
**Pull request by nikpivkin**
In this PR: 
- Terraform and CloudFormation examples moved from `cf.go` and `tf.go` to `yaml`, 
- all checks now refer to the yaml examples
- added command for formatting examples

Although all the examples for a single check are in a single file, we need to reference it from multiple check fields. I suggest adding a new `examples` field that will point to a single file, while maintaining support for the current method of referencing examples for backwards compatibility.

Old example files will be deleted in another PR as they are still referenced by Go checks.

### CODE REVIEW

**Comment by nikpivkin** [comment]
Will be ready for review after the release of Trivy v0.57

**Comment by simar7** [comment]
One thing to keep in mind with the examples is the avd generator. I believe it uses the go files as well. Could you confirm that @nikpivkin?

**Comment by nikpivkin** [comment]
@simar7 I'll check, but as far as I remember avd-generator uses generated md files.

**Comment by nikpivkin** [comment]
avd-generator uses only generated `.md` files https://github.com/aquasecurity/avd-generator/blob/main/docGen/defsec.go#L151-L161

**Comment by nikpivkin** [comment]
Maybe we should change the file schema to the following?
```yaml
id: avdid
examples:
   terraform:
   cloudformation:
```

This will allow us to associate examples and checks without using the `trivy` and `trivy-checks` packages to run the tests. To do this now, we need to load all the checks and then load all the examples based on the check metadata.

**Comment by simar7** [comment]
> Maybe we should change the file schema to the following?
> 
> ```yaml
> id: avdid
> examples:
>    terraform:
>    cloudformation:
> ```
> 
> This will allow us to associate examples and checks without using the `trivy` and `trivy-checks` packages to run the tests. To do this now, we need to load all the checks and then load all the examples based on the check metadata.

It makes sense to me but we should make an announcement regarding this change as we will be changing the metadata schema. I suggest let's do it in a separate PR.

**Review by simar7 — APPROVED** [review]
🙏🏼

**Pull request merged**
