### PR TITLE
fix(checks): invert logic of AVD-KCV-0030

### PR DESCRIPTION
**Pull request by kapistka**
We found an incorrect rego-expression when checking the parameter --encryption-provider-config

### CODE REVIEW

**Comment by nikpivkin** [comment]
Hi @kapistka! Nice catch

Can you update the tests?

**Comment by kapistka** [comment]
> Hi @kapistka! Nice catch
> 
> Can you update the tests?
done)

**Comment by kapistka** [comment]
CLA done)

**Comment by kapistka** [comment]
I can't understand why checks failed.

**Comment by nikpivkin** [comment]
@kapistka Can you run `make fmt-rego` and push the changes?

**Comment by nikpivkin** [comment]
@simar7 I've updated it, can you take a look?

**Review by simar7 — APPROVED** [review]

**Pull request merged**
